---

  - name: "Задача-сборщик информации с других машин"
    hosts: all
    gather_facts: no
    tasks:
      - name: "Запуск скрипта-сборищика версий"
        script: ../scripts/get_versions.sh
        register: script_output

      - name: "Получение файла с версиями"
        delegate_to: localhost
        copy:
          content: "{{ script_output.stdout }}"
          dest: "../data/incoming/{{ ansible_host }}.json"
